export type Direction = {
  id: string;
  name: string;
  label: string;
  thesis: string;
  firstImpression: string;
  motion: string;
  system: string;
  type: string;
  accent: string;
  bestFor: string;
  watchOut: string;
  stack: string[];
};

export const directions: Direction[] = [
  {
    id: 'flight-lab',
    name: 'The Flight Lab',
    label: 'Flagship product story',
    thesis: 'Turn Golfie into the undeniable proof that Damian can invent, engineer, and ship a difficult product from first principles.',
    firstImpression: 'A ball launches through an editorial trajectory field while live telemetry resolves around the arc.',
    motion: 'A single continuous flight curve orchestrates the intro, section transitions, cursor response, and project reveals.',
    system: 'OLED black, phosphor lime, hairline grids, large humanist sans, compact instrument labels.',
    type: 'Instrument Sans + DM Mono',
    accent: '#b7ff5a',
    bestFor: 'The strongest founder narrative and the most ownable visual identity.',
    watchOut: 'Needs disciplined performance budgets so the physics never overwhelms the story.',
    stack: ['Motion', 'Anime.js', 'R3F', 'WebGL'],
  },
  {
    id: 'twin-lens',
    name: 'Twin Lens',
    label: 'Computer-vision cinema',
    thesis: 'Make the act of seeing, synchronizing, and reconstructing reality the central metaphor for the portfolio.',
    firstImpression: 'Two camera planes search independently, lock onto one object, then triangulate the headline in 3D space.',
    motion: 'Reticles acquire targets, split panels drift at different depth, and focus states snap with optical precision.',
    system: 'Ink black, ultraviolet blue, split-screen framing, circular optics, crisp condensed metadata.',
    type: 'Manrope + DM Mono',
    accent: '#8c7bff',
    bestFor: 'A specialist positioning around AI, computer vision, and spatial computing.',
    watchOut: 'The visual metaphor is narrower than Damian’s full-stack and product range.',
    stack: ['Motion', 'SVG filters', 'Canvas', 'Web Audio'],
  },
  {
    id: 'systems-foundry',
    name: 'Systems Foundry',
    label: 'Editorial engineering',
    thesis: 'Present each product as a machine made of decisions, constraints, failures, and measurable outcomes.',
    firstImpression: 'Oversized type and an animated assembly diagram turn the homepage into a premium engineering journal cover.',
    motion: 'Mechanical wipes, ruler ticks, conveyor-like project transitions, and deliberately stepped counters.',
    system: 'Warm paper, carbon black, safety orange, visible rules, typographic scale, almost no decoration.',
    type: 'Newsreader + Instrument Sans',
    accent: '#ff5c35',
    bestFor: 'Clear case studies, mature product judgment, and excellent long-form readability.',
    watchOut: 'Less immediately “techno-futurist” than the darker directions.',
    stack: ['Anime.js', 'CSS masks', 'View Transitions', 'SVG'],
  },
  {
    id: 'project-orbit',
    name: 'Project Orbit',
    label: 'Spatial portfolio map',
    thesis: 'Show that every project belongs to one connected practice: sensing, modeling, systems, and product craft.',
    firstImpression: 'Projects orbit a luminous Damian core; moving the pointer changes depth and reveals hidden relationships.',
    motion: 'Inertial orbiting, magnetic node selection, depth-of-field transitions, and semantic zoom into case studies.',
    system: 'Deep navy, ice blue, radial coordinates, soft light, restrained glass only where it conveys depth.',
    type: 'Instrument Sans + DM Mono',
    accent: '#77d8ff',
    bestFor: 'A memorable nonlinear browse experience with strong exploration value.',
    watchOut: 'Needs a parallel linear path for accessibility and recruiters who want speed.',
    stack: ['R3F', 'Motion', 'WebGL', 'Spatial index'],
  },
  {
    id: 'kinetic-thesis',
    name: 'Kinetic Thesis',
    label: 'Typography as interface',
    thesis: 'Make Damian’s point of view—not a technology list—the first thing visitors remember.',
    firstImpression: 'The phrase “I make hard things real” recomposes itself around a live project reel as the pointer moves.',
    motion: 'Variable-font compression, masked word swaps, sharp editorial cuts, and scroll-controlled type choreography.',
    system: 'White field, near-black type, signal red, radical scale changes, cropped edges, generous negative space.',
    type: 'Instrument Sans variable + DM Mono',
    accent: '#f04438',
    bestFor: 'High confidence, creative-technology roles, and an Awwwards-style first impression.',
    watchOut: 'The writing must be exceptional; weak copy cannot hide behind the layout.',
    stack: ['Motion', 'Anime.js', 'CSS masks', 'Variable fonts'],
  },
  {
    id: 'founder-os',
    name: 'Founder OS',
    label: 'Productivity interface',
    thesis: 'Frame the portfolio as Damian’s live operating environment: projects, experiments, writing, and contact are tools.',
    firstImpression: 'A calm desktop assembles itself into a command center with Golfie running as the active process.',
    motion: 'Spring-loaded windows, command-palette morphs, contextual previews, and keyboard-first navigation.',
    system: 'Graphite, warm amber, compact utility type, soft panels, high information density with disciplined hierarchy.',
    type: 'Manrope + DM Mono',
    accent: '#ffbd59',
    bestFor: 'Recruiter usability, deep content, repeat visits, and a strong builder personality.',
    watchOut: 'Desktop metaphors can become gimmicky if every interaction imitates an operating system.',
    stack: ['Motion', 'Command menu', 'Indexed search', 'Local state'],
  },
  {
    id: 'build-chronicle',
    name: 'Build Chronicle',
    label: 'Evidence-led narrative',
    thesis: 'Let artifacts, dates, experiments, and decisions prove growth without ever reading like a résumé.',
    firstImpression: 'A dated field note opens mid-thought, with project evidence pinned into a living chronological margin.',
    motion: 'Page turns, sticky annotations, ink-line drawings, and quiet scroll reveals that reward close reading.',
    system: 'Mineral paper, bottle green, serif narrative type, marginalia, stamps, diagrams, and editorial photography slots.',
    type: 'Newsreader + DM Mono',
    accent: '#167a52',
    bestFor: 'Authenticity, depth, writing, and communicating how Damian thinks over time.',
    watchOut: 'Requires real process artifacts and concise editing to avoid becoming a blog archive.',
    stack: ['Motion', 'CSS scroll timelines', 'MDX', 'Image optimization'],
  },
  {
    id: 'optical-field',
    name: 'Optical Field',
    label: 'Experimental product art',
    thesis: 'Translate computer vision into a softer, art-directed world of refraction, focus, and changing perception.',
    firstImpression: 'A translucent optical object bends the grid, color, and headline beneath it as it follows the pointer.',
    motion: 'Slow lens drift, refractive cursor response, focus pulls, chromatic edge separation, and liquid page transitions.',
    system: 'Porcelain, charcoal, spectral violet, translucent layers, rounded geometry, and gallery-like spacing.',
    type: 'Manrope + Newsreader',
    accent: '#6d4aff',
    bestFor: 'The most artful, design-forward expression without using cliché developer visuals.',
    watchOut: 'Complex shader effects need careful fallbacks and can compete with project detail.',
    stack: ['WebGL shaders', 'Motion', 'SVG filters', 'CSS Houdini'],
  },
  {
    id: 'telemetry-deck',
    name: 'Telemetry Deck',
    label: 'Live systems proof',
    thesis: 'Make the portfolio feel like a sophisticated product already running—not a page describing past work.',
    firstImpression: 'Live trajectory telemetry streams into modular instruments while a launch event drives the whole layout.',
    motion: 'Data ticks, waveform traces, scanning sweeps, modular panel rearrangement, and precise state transitions.',
    system: 'Black, cool gray, cyan, dense modular cards, technical numerals, and bright data only where it matters.',
    type: 'Manrope + DM Mono',
    accent: '#25e6da',
    bestFor: 'Engineering credibility, interactive demos, metrics, and systems-minded employers.',
    watchOut: 'The visual density needs strong progressive disclosure on smaller screens.',
    stack: ['Anime.js', 'Canvas', 'Motion', 'Web Workers'],
  },
  {
    id: 'quiet-monolith',
    name: 'Quiet Monolith',
    label: 'Cinematic restraint',
    thesis: 'Create maximum confidence with almost nothing: one object, one sentence, and immaculate pacing.',
    firstImpression: 'A solitary golf ball emerges from darkness; its dimple field becomes a constellation of projects.',
    motion: 'Long cinematic easing, subtle material shifts, scroll-directed camera moves, and near-silent microinteractions.',
    system: 'True black, bone white, pale gold, monumental type, sculptural light, and extreme negative space.',
    type: 'Instrument Sans + Newsreader',
    accent: '#d8c49a',
    bestFor: 'Premium founder positioning and the most timeless, Apple-adjacent direction.',
    watchOut: 'Requires excellent 3D art direction and ruthless content reduction.',
    stack: ['R3F', 'GLSL', 'Motion', 'Lenis'],
  },
];
